export enum EVENTS {
        NONE = "NONE",
    // ECONOMY EVENTS
        GOLD_BUYER = "GOLD_BUYER",
        HUMAN_BUYER = "HUMAN_BUYER",
        SCAVENGED_BUYER = "SCAVENGED_BUYER",
        GOLD_SELLER = "GOLD_SELLER",
        HUMAN_SELLER = "HUMAN_SELLER",
        SCAVENGED_SELLER = "SCAVENGED_SELLER",

    // TOWN EVENTS
        ENTHUSIASTIC_MASONRY = "ENTHUSIASTIC_MASONRY",
        EXCEPTIONNAL_HARVEST = "EXCEPTIONNAL_HARVEST",
        GOOD_OMEN = "GOOD_OMEN",
        STRANGE_ORE = "STRANGE_ORE",

    // ARMY EVENTS
        RAINSTORM = "RAINSTORM",
        BURNING_SUN = "BURNING_SUN",
    }