export enum EVENTS {
        NONE = "NONE",

    // ECONOMY EVENTS
        HUMAN_BUYER = "HUMAN_BUYER",
        SCAVENGED_BUYER = "SCAVENGED_BUYER",
        HUMAN_SELLER = "HUMAN_SELLER",
        SCAVENGED_SELLER = "SCAVENGED_SELLER",

    // TOWN EVENTS
        ENTHUSIASTIC_MASONRY = "ENTHUSIASTIC_MASONRY",
        EXCEPTIONNAL_HARVEST = "EXCEPTIONNAL_HARVEST",
        GOOD_OMEN = "GOOD_OMEN",
        STRANGE_ORE = "STRANGE_ORE",

    // TAROT READINGS
        THE_FOOL = "THE_FOOL",
        THE_MAGICIAN = "THE_MAGICIAN",
        THE_HIGH_PRIESTESS = "THE_HIGH_PRIESTESS",
        // THE_EMPRESS = "THE_EMPRESS",
        THE_EMPEROR = "THE_EMPEROR",
        // THE_HIEROPHANT = "THE_HIEROPHANT",
        // THE_LOVERS = "THE_LOVERS",
        // THE_CHARIOT = "THE_CHARIOT",
        // STRENGTH = "STRENGTH",
        JUSTICE = "JUSTICE",
        JUDGEMENT = "JUDGEMENT",
        THE_HERMIT = "THE_HERMIT",
        // WHEEL_OF_FORTUNE = "WHEEL_OF_FORTUNE",
        // THE_HANGED_MAN = "THE_HANGED_MAN",
        // DEATH = "DEATH",
        // TEMPERANCE = "TEMPERANCE",
        THE_DEVIL = "THE_DEVIL",
        // THE_TOWER = "THE_TOWER",
        // THE_STARS = "THE_STARS",
        THE_MOON = "THE_MOON",
        // THE_SUN = "THE_SUN",
        THE_WORLD = "THE_WORLD",
    }